
if {[file exists "work"]} {
    vdel -lib work -all
}

vlib work

vmap work work

# ---------------------------------------------------------------------------
# DPI-C shared library — built from src/model/cic_model_dpi.cpp
# Includes rtl/tb/cic_model.hpp (generated by cic_generator.py --tb).
# No Python dependency.
# ---------------------------------------------------------------------------

# cl.exe — prefer CL_EXE env var, otherwise search VS install directories
if {[info exists env(CL_EXE)] && ![string equal $env(CL_EXE) ""]} {
    set cl_exe [string map {\\ /} $env(CL_EXE)]
} else {
    set _cl_candidates [glob -nocomplain \
        {C:/Program Files/Microsoft Visual Studio/*/BuildTools/VC/Tools/MSVC/*/bin/Hostx64/x64/cl.exe} \
        {C:/Program Files/Microsoft Visual Studio/*/Community/VC/Tools/MSVC/*/bin/Hostx64/x64/cl.exe} \
        {C:/Program Files/Microsoft Visual Studio/*/Professional/VC/Tools/MSVC/*/bin/Hostx64/x64/cl.exe} \
        {C:/Program Files (x86)/Microsoft Visual Studio/*/BuildTools/VC/Tools/MSVC/*/bin/Hostx64/x64/cl.exe} \
        {C:/Program Files (x86)/Microsoft Visual Studio/*/Community/VC/Tools/MSVC/*/bin/Hostx64/x64/cl.exe}]
    if {[llength $_cl_candidates] == 0} {
        puts "ERROR: cl.exe not found. Install MSVC Build Tools or set CL_EXE to the full path."
        quit -code 1
    }
    set cl_exe [lindex [lsort $_cl_candidates] end]
}

# Questa include dir — prefer QUESTA_INC env var, otherwise search
if {[info exists env(QUESTA_INC)] && ![string equal $env(QUESTA_INC) ""]} {
    set questa_inc [string map {\\ /} $env(QUESTA_INC)]
} else {
    set _candidates [glob -nocomplain \
        {C:/questasim64_*/include} \
        {C:/questasim_*/include} \
        {C:/Modeltech*/include}]
    if {[llength $_candidates] == 0} {
        puts "ERROR: svdpi.h not found. Set QUESTA_INC to the Questa include directory."
        quit -code 1
    }
    set questa_inc [lindex $_candidates 0]
}

# Derive vcvars64.bat from cl.exe path (6 levels up from Hostx64/x64/)
set _vc_root [file dirname $cl_exe]
for {set _i 0} {$_i < 6} {incr _i} { set _vc_root [file dirname $_vc_root] }
set vcvars_bat "${_vc_root}/Auxiliary/Build/vcvars64.bat"

set dpi_src  "../src/model/cic_model_dpi.cpp"
set dpi_dll  "cic_model_dpi.dll"
set dpi_inc  "../rtl/tb"

puts "Building DPI shared library: $dpi_dll"
puts "  cl.exe    : $cl_exe"
puts "  vcvars    : $vcvars_bat"
puts "  questa inc: $questa_inc"

# Write a temp batch file: initialise the MSVC environment then call cl.exe
set _bat [file nativename [file join [pwd] _dpi_build_tmp.bat]]
set _fd [open $_bat w]
puts $_fd "@echo off"
puts $_fd "call \"[file nativename $vcvars_bat]\" >nul 2>&1"
puts $_fd "\"[file nativename $cl_exe]\" /LD /MD /nologo \
/I \"[file nativename $questa_inc]\" \
/I \"[file nativename $dpi_inc]\" \
\"[file nativename [file normalize $dpi_src]]\" \
/link /OUT:\"[file nativename [file normalize $dpi_dll]]\""
close $_fd

if {[catch {exec cmd /c $_bat} _build_err]} {
    catch {file delete $_bat}
    puts "ERROR: DPI build failed —\n$_build_err"
    quit -code 1
}
catch {file delete $_bat}
puts "DPI shared library built successfully."

# ---------------------------------------------------------------------------
# Simulation mode
#   $1 = UVM test name                   (required)
#   $2 = sim mode: rtl | post            (optional, default: rtl)
#   $3 = SDF timing corner (post only)   (optional, default: nom_tt_025C_1v80)
#        choices: nom_tt_025C_1v80  max_ss_100C_1v60  max_ff_n40C_1v95
#                 min_tt_025C_1v80  min_ss_100C_1v60  min_ff_n40C_1v95
#                 nom_ff_n40C_1v95  nom_ss_100C_1v60  nom_tt_025C_1v80
# ---------------------------------------------------------------------------

if {[info exists 2] && ![string equal "$2" ""]} {
    set sim_mode "$2"
} else {
    set sim_mode "rtl"
}

if {[info exists 3] && ![string equal "$3" ""]} {
    set sdf_corner "$3"
} else {
    set sdf_corner "nom_tt_025C_1v80"
}

if {[string equal $sim_mode "post"]} {
    if {![info exists env(PDK_ROOT)] || [string equal $env(PDK_ROOT) ""]} {
        puts "ERROR: PDK_ROOT environment variable is not set."
        puts "       Set it to your volare install root, e.g.:"
        puts "         set PDK_ROOT=%USERPROFILE%\\.volare"
        quit -code 1
    }
    set pdk_root $env(PDK_ROOT)
    set sky130_lib "${pdk_root}/sky130A/libs.ref/sky130_fd_sc_hd/verilog/sky130_fd_sc_hd.v"
    set rtl_filelist "post.f"
    set compile_flags "-sv -work work -svinputport=net +acc"
    set compile_cmd "vlog $compile_flags $sky130_lib -f $rtl_filelist -f tb.f"
} else {
    set rtl_filelist "rtl.f"
    set compile_flags "-sv -work work -lint -svinputport=net +acc"
    set compile_cmd "vlog $compile_flags -f $rtl_filelist -f tb.f"
}

if {[catch {eval $compile_cmd} compile_err]} {
    puts "ERROR: Compilation failed — $compile_err"
    quit -code 1
}

vopt work.pdm_to_pcm_top_tb -o pdm_to_pcm_top_tb_opt -designfile design.bin -debug

if {[string equal $sim_mode "post"]} {
    set sdf_file "../rtl_post/sdf/${sdf_corner}/tt_um_top__${sdf_corner}.sdf"
    vsim work.pdm_to_pcm_top_tb \
        -sv_seed random \
        -sv_lib cic_model_dpi \
        -voptargs=+acc \
        -onfinish exit \
        -qwavedb=+signal+cells+uvm_configdb+class+transaction+uvm_schematic+uvm_register+uvm_factory+memory \
        +UVM_NO_RELNOTES \
        +UVM_TESTNAME=$1 \
        +UVM_MAX_QUIT_COUNT=1 \
        -sdfmax /pdm_to_pcm_top_tb/dut/tt_um_top_inst=${sdf_file} \
} else {
    vsim work.pdm_to_pcm_top_tb \
        -sv_seed random \
        -sv_lib cic_model_dpi \
        -voptargs=+acc \
        -onfinish exit \
        -qwavedb=+signal+cells+uvm_configdb+class+transaction+uvm_schematic+uvm_register+uvm_factory+memory \
        +UVM_NO_RELNOTES \
        +UVM_TESTNAME=$1 \
        +UVM_MAX_QUIT_COUNT=1 \
}

run -all
quit
