// Auto-generated by cic_generator.py — DO NOT EDIT BY HAND
// CIC fixed-point reference model (SystemVerilog class): N=3, R=32, M=1, Bin=1, Bout=8
// Stage widths (integrators): [16, 16, 14]
// Stage widths (comb):        [12, 11, 10]
// Max accumulator width: 16  |  Output bit-select drops 2 LSBs
//
// Bit-accurate with cic.sv (PIPELINE_ENABLE=0).
// UVM-compatible class — one instance per channel; no external dependencies.

`ifndef CIC_MODEL_SVH
`define CIC_MODEL_SVH

// ---------------------------------------------------------------------------
// cic_model — bit-accurate CIC decimation filter reference model
//
//   new()                         — constructor; calls reset().
//   reset()                       — zeros all internal state.
//   step(pdm_in, pcm_out) : bit   — process one PDM input bit.
//                                   Sets pcm_out and returns 1 every R calls;
//                                   returns 0 on all other calls.
// ---------------------------------------------------------------------------
class cic_model;

    // -----------------------------------------------------------------------
    // Parameters (baked in at generation time)
    // -----------------------------------------------------------------------
    localparam int N    = 3;
    localparam int R    = 32;
    localparam int M    = 1;
    localparam int Bin  = 1;
    localparam int Bout = 8;

    localparam int INTEG_WIDTHS[3] = '{16, 16, 14};
    localparam int COMB_WIDTHS[3]  = '{12, 11, 10};
    localparam int OUTPUT_DROP       = 2;

    // -----------------------------------------------------------------------
    // Internal state
    // -----------------------------------------------------------------------
    protected longint _integ[3];
    protected longint _comb_dly[3][1];
    protected int     _dec_cnt;

    // -----------------------------------------------------------------------
    // Constructor
    // -----------------------------------------------------------------------
    function new();
        reset();
    endfunction

    // -----------------------------------------------------------------------
    // reset — zero all internal state
    // -----------------------------------------------------------------------
    function void reset();
        for (int i = 0; i < N; i++) begin
            _integ[i] = 0;
            for (int m = 0; m < M; m++) _comb_dly[i][m] = 0;
        end
        _dec_cnt = 0;
    endfunction

    // -----------------------------------------------------------------------
    // step — process one PDM input bit
    //
    //   pdm_in  : 1-bit PDM input (0 or 1)
    //   pcm_out : signed int; written when return value is 1
    //   returns : 1 when a new PCM sample is ready, 0 otherwise
    // -----------------------------------------------------------------------
    function bit step(input bit pdm_in, output int pcm_out);
        longint feed[3];
        longint last_integ_pre;
        longint comb_val;
        bit     dec_en;
        int     prev_w;
        longint feed_val;
        longint dly_out;

        // --- Integrators: evaluate all feeds from pre-update state, then update ---
        // Mirrors SV always_ff semantics: all RHS evaluated from pre-clock-edge values.
        feed[0] = pdm_in ? longint'(1) : longint'(-1);
        for (int i = 1; i < N; i++)
            feed[i] = top_bits(_integ[i-1], INTEG_WIDTHS[i-1], INTEG_WIDTHS[i]);
        last_integ_pre = _integ[N-1];
        for (int i = 0; i < N; i++)
            _integ[i] = wrap_bits(_integ[i] + feed[i], INTEG_WIDTHS[i]);

        // --- Decimation counter ---
        dec_en   = (_dec_cnt == R - 1);
        _dec_cnt = dec_en ? 0 : _dec_cnt + 1;
        if (!dec_en) return 0;

        // --- Comb stages (run every R-th input) ---
        // RTL comb reads pre-clock-edge integrator value (the R-th accumulated sample).
        comb_val = last_integ_pre;
        for (int i = 0; i < N; i++) begin
            prev_w   = (i == 0) ? INTEG_WIDTHS[N-1] : COMB_WIDTHS[i-1];
            feed_val = top_bits(comb_val, prev_w, COMB_WIDTHS[i]);
            dly_out  = _comb_dly[i][M-1];
            for (int m = M-1; m > 0; m--) _comb_dly[i][m] = _comb_dly[i][m-1];
            _comb_dly[i][0] = feed_val;
            comb_val = wrap_bits(feed_val - dly_out, COMB_WIDTHS[i]);
        end

        // --- Output: top Bout bits of the final comb stage ---
        pcm_out = int'(top_bits(comb_val, COMB_WIDTHS[N-1], Bout));
        return 1;
    endfunction

    // -----------------------------------------------------------------------
    // wrap_bits — wrap v to w signed bits (SV register truncation equivalent)
    // -----------------------------------------------------------------------
    protected function longint wrap_bits(input longint v, input int w);
        longint mask;
        if (w <= 0 || w >= 64) return v;
        mask = (longint'(1) << w) - 1;
        v    = v & mask;
        if ((v >> (w - 1)) & 1) v = v | ~mask;  // sign-extend
        return v;
    endfunction

    // -----------------------------------------------------------------------
    // top_bits — extract top to_w bits from a from_w-bit signed value
    //            equivalent to SV bit-select v[from_w-1 : from_w-to_w]
    // -----------------------------------------------------------------------
    protected function longint top_bits(input longint v, input int from_w, input int to_w);
        v = wrap_bits(v, from_w);
        if (from_w > to_w) v = v >>> (from_w - to_w);  // arithmetic right-shift
        return wrap_bits(v, to_w);
    endfunction

endclass : cic_model

`endif  // CIC_MODEL_SVH
