
// This file was autogenerated by PeakRDL-uvm
package pdm_to_pcm_reg_pkg;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // reg - pdm_to_pcm_reg.control
    class pdm_to_pcm_reg__control extends uvm_reg;
        rand uvm_reg_field enable;

        function new(string name = "pdm_to_pcm_reg__control");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.enable = new("enable");
            this.enable.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pdm_to_pcm_reg__control

    // reg - pdm_to_pcm_reg.nco_control
    class pdm_to_pcm_reg__nco_control extends uvm_reg;
        rand uvm_reg_field low;
        rand uvm_reg_field high;

        function new(string name = "pdm_to_pcm_reg__nco_control");
            super.new(name, 16, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.low = new("low");
            this.low.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 0);
            this.high = new("high");
            this.high.configure(this, 8, 8, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pdm_to_pcm_reg__nco_control

    // reg - pdm_to_pcm_reg.data_right
    class pdm_to_pcm_reg__data_right extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "pdm_to_pcm_reg__data_right");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 8, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pdm_to_pcm_reg__data_right

    // reg - pdm_to_pcm_reg.data_left
    class pdm_to_pcm_reg__data_left extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "pdm_to_pcm_reg__data_left");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 8, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pdm_to_pcm_reg__data_left

    // reg - pdm_to_pcm_reg.id
    class pdm_to_pcm_reg__id extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "pdm_to_pcm_reg__id");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 8, 0, "RO", 0, 'hda, 1, 1, 0);
        endfunction : build
    endclass : pdm_to_pcm_reg__id

    // addrmap - pdm_to_pcm_reg
    class pdm_to_pcm_reg extends uvm_reg_block;
        rand pdm_to_pcm_reg__control control;
        rand pdm_to_pcm_reg__nco_control nco_control;
        rand pdm_to_pcm_reg__data_right data_right;
        rand pdm_to_pcm_reg__data_left data_left;
        rand pdm_to_pcm_reg__id id;

        function new(string name = "pdm_to_pcm_reg");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 1, UVM_LITTLE_ENDIAN);
            this.control = new("control");
            this.control.configure(this);
            this.control.add_hdl_path_slice("control_enable", 0, 1);
            this.control.build();
            this.default_map.add_reg(this.control, 'h0);
            this.nco_control = new("nco_control");
            this.nco_control.configure(this);
            this.nco_control.add_hdl_path_slice("nco_control_low", 0, 8);
            this.nco_control.add_hdl_path_slice("nco_control_high", 8, 8);
            this.nco_control.build();
            this.default_map.add_reg(this.nco_control, 'h2);
            this.data_right = new("data_right");
            this.data_right.configure(this);
            this.data_right.add_hdl_path_slice("data_right_value", 0, 8);
            this.data_right.build();
            this.default_map.add_reg(this.data_right, 'h4);
            this.data_left = new("data_left");
            this.data_left.configure(this);
            this.data_left.add_hdl_path_slice("data_left_value", 0, 8);
            this.data_left.build();
            this.default_map.add_reg(this.data_left, 'h5);
            this.id = new("id");
            this.id.configure(this);
            this.id.add_hdl_path_slice("id_value", 0, 8);
            this.id.build();
            this.default_map.add_reg(this.id, 'h6);
        endfunction : build
    endclass : pdm_to_pcm_reg

endpackage: pdm_to_pcm_reg_pkg
