
// This file was autogenerated by PeakRDL-uvm
package pdm_to_pcm_reg_pkg;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // reg - pdm_to_pcm_reg::control
    class pdm_to_pcm_reg__control extends uvm_reg;
        rand uvm_reg_field enable;
        rand uvm_reg_field divider;

        function new(string name = "pdm_to_pcm_reg__control");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.enable = new("enable");
            this.enable.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            this.divider = new("divider");
            this.divider.configure(this, 2, 1, "RW", 0, 'h0, 0, 1, 0);
        endfunction : build
    endclass : pdm_to_pcm_reg__control

    // reg - pdm_to_pcm_reg::data
    class pdm_to_pcm_reg__data extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "pdm_to_pcm_reg__data");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 8, 0, "RO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pdm_to_pcm_reg__data

    // reg - pdm_to_pcm_reg::id
    class pdm_to_pcm_reg__id extends uvm_reg;
        rand uvm_reg_field ID;

        function new(string name = "pdm_to_pcm_reg__id");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.ID = new("ID");
            this.ID.configure(this, 8, 0, "RO", 0, 'hda, 1, 1, 0);
        endfunction : build
    endclass : pdm_to_pcm_reg__id

    // addrmap - pdm_to_pcm_reg
    class pdm_to_pcm_reg extends uvm_reg_block;
        rand pdm_to_pcm_reg__control control;
        rand pdm_to_pcm_reg__data data;
        rand pdm_to_pcm_reg__id id;

        function new(string name = "pdm_to_pcm_reg");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 1, UVM_LITTLE_ENDIAN);
            this.control = new("control");
            this.control.configure(this);

            this.control.build();
            this.default_map.add_reg(this.control, 'h0);
            this.data = new("data");
            this.data.configure(this);

            this.data.build();
            this.default_map.add_reg(this.data, 'h1);
            this.id = new("id");
            this.id.configure(this);

            this.id.build();
            this.default_map.add_reg(this.id, 'h2);
        endfunction : build
    endclass : pdm_to_pcm_reg

endpackage: pdm_to_pcm_reg_pkg
